version: '3.1'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
    links:
      - "mongodb:database"


volumes:
  mongo_data:
  